apiVersion: apps/v1
kind: Deployment
metadata:
  name: fooapp
  labels:
    app: fooapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fooapp
  strategy:
    type: Recreate
  template:
    metadata:
      name: fooapp
      labels:
        app: fooapp
    spec:
      restartPolicy: Always
      containers:
      - image: fooapp
        name: fooapp
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        tty: true
        stdin: true
      terminationGracePeriodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fooapp
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: foo-svc.maaladv.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fooapp
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fooapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fooapp
